### ISSUE TITLE
False positive caused by loop invariant

### ISSUE THREAD

**Issue by ghost** [imdea-software/verifying-constant-time#5]
Hello:

I can see that this version of ct-verif is no longer maintained, but I was hoping to generate some results that are based on the method in the paper [https://www.usenix.org/conference/usenixsecurity16/technical-sessions/presentation/almeida](url)

I am having trouble verifying the following:

```
void
secret_indep (struct STRUCT *p, struct STRUCT *s) {
    
    int i = 0;
    for( i = 0; i<32; i++ )
        if( p->arr[i] != 0 )
            break;
}

/**
 * ct-verif is expected to verify here.
 */
void
secret_indep_wrapper ( int *pub, int *sec) {
    
    //    __disjoint_regions(pub,32,sec,32);
    public_in(__SMACK_value(pub));
    public_in(__SMACK_value(sec));
    
    public_in(__SMACK_values(pub,32));
    public_in(__SMACK_values(sec,32));
    
    
    struct STRUCT OBJ_pub = {pub};
    struct STRUCT *p = &OBJ_pub;
    
    struct STRUCT OBJ_sec = {sec};
    struct STRUCT *s = &OBJ_sec;
    
    
    secret_indep (p,s);
}
```

As you can see I ended up marking everything public but still got an error pointing to the line:

`    for( i = 0; i<32; i++ )
`

It says  

`Error BP5005: This loop invariant might not be maintained by the loop.
`

Any ideas? Your help would be greatly appreciated.

**Comment by ghost** [comment]
I made a shorter example that captures the same issue:

```
void
func (int *p) {
    
    int i;
    for( i=10; i<20; i++ ) {
        if( p[i] != 0 )
            break;
    }
}

void
secret_indep_wrapper ( int *p) {
    
    public_in(__SMACK_value(p));
    public_in(__SMACK_values(p,32));
    
    func (p);
}
```

still
`    Error BP5005: This loop invariant might not be maintained by the loop.
`
pointing to 
`    for( i=10; i<20; i++ ) {
`

**Comment by fdupress** [comment]
Hi Ernie,

The issue here is that the proof of security requires Boogie to first infer
that the value of i within the loop body will always remain between 0 and
31 (which is the range you declared as public). In this case, it is true (i
will in fact always be between 10 and 20 when p[i] gets accessed), but the
prover simply doesn't know it at the point where it tried to discharge the
proof obligation.

There might be a facility in smack to pass around the appropriate loop
invariant, but I am not sure how it would look.

François

**Comment by michael-emmi** [comment]
Hi!
There is an (experimental) way to add code contracts, including loop invariants, with Smack. The following code illustrates this, and verifies.

```c
#include <ct-verif.h>
#include <smack-contracts.h>

void
func (int *p) {
    
    int i;
    for( i=10; i<20; i++ ) {
        invariant (i >= 0);
        if( p[i] != 0 )
            break;
    }
}

void
secret_indep_wrapper ( int *p) {
    
    public_in(__SMACK_value(p));
    public_in(__SMACK_values(p,32));
    
    func (p);
}
```

**Comment by ghost** [comment]
Hi,
Thank you for the quick responses, this looks great!

```
Boogie program verifier version 2.3.0.61016, Copyright (c) 2003-2014, Microsoft.
/home/vagrant/ct-verif/examples/base-examples/forloop-instrumented.bpl(323,54): error: invalid UnaryExpression
1 parse errors detected in /home/vagrant/ct-verif/examples/base-examples/forloop-instrumented.bpl
```

I got an error on your example.  Are you using an updated version of smack?  I tried that too and got a BAM error:

```
/home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bpl/analysis/call_graph_construction.rb:18:in `block in run!': undefined method `callers' for nil:NilClass (NoMethodError)
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:160:in `yield'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:160:in `enumerate'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:166:in `block (2 levels) in enumerate'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:166:in `each'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:166:in `block in enumerate'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:161:in `each'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:161:in `enumerate'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:166:in `block (2 levels) in enumerate'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:166:in `each'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:166:in `block in enumerate'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:161:in `each'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:161:in `enumerate'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:164:in `block in enumerate'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:161:in `each'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:161:in `enumerate'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:166:in `block (2 levels) in enumerate'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:166:in `each'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:166:in `block in enumerate'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:161:in `each'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:161:in `enumerate'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:114:in `block in each'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:116:in `each'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:116:in `each'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bpl/ast/node.rb:116:in `each'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bpl/analysis/call_graph_construction.rb:12:in `run!'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bam.rb:159:in `block (3 levels) in <top (required)>'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bam/prelude.rb:135:in `timed'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bam.rb:158:in `block (2 levels) in <top (required)>'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bam.rb:156:in `each'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bam.rb:156:in `block in <top (required)>'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bam.rb:155:in `each'
	from /home/vagrant/ct-verif/tools/bam-bam-boogieman/lib/bam.rb:155:in `<top (required)>'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/vagrant/ct-verif/bin/../tools/bam-bam-boogieman//bin/bam:4:in `<main>'
```

**Comment by michael-emmi** [comment]
Are you using the latest versions of Smack and Bam?

```bash
$ smack --version && bam --version
SMACK version 1.9.3
bam version 1.0.7
```

**Comment by ghost** [comment]
No, I wasn't using the latest version of Bam.  I updated and am now trying to resolve a ruby error(I have no experience with ruby):

```
/usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bundler/setup (LoadError)
```

I'll try to resolve this and confirm that I can get it to work on my end

**Comment by michael-emmi** [comment]
I recommend following the *Development* instructions in Bam’s README.md; specifically, run `bin/setup` then `bundle exec rake install`. Your version of Ruby 2.2 should be fine.

Alternatively, you might try to just install Bam from the Gem package manager without even cloning the GitHub repo: `gem install bam-bam-boogieman`.

**Comment by ghost** [comment]
Great, thanks!  Sorry for the delay.  

Updating smack and bam and then adding the invariant above fixes this issue.

**Comment by Jerry-zhxf** [comment]
> Hi! There is an (experimental) way to add code contracts, including loop invariants, with Smack. The following code illustrates this, and verifies.
> 
> ```c
> #include <ct-verif.h>
> #include <smack-contracts.h>
> 
> void
> func (int *p) {
>     
>     int i;
>     for( i=10; i<20; i++ ) {
>         invariant (i >= 0);
>         if( p[i] != 0 )
>             break;
>     }
> }
> 
> void
> secret_indep_wrapper ( int *p) {
>     
>     public_in(__SMACK_value(p));
>     public_in(__SMACK_values(p,32));
>     
>     func (p);
> }
> ```

Hello, I tried to run your this example but get the different error result. And I don't know why.
And my smack and bam version is
SMACK version 2.4.0
bam version 1.0.10
```
Warning: could not resolve constant/variable $load.i32
/var/lib/gems/2.3.0/gems/bam-bam-boogieman-1.0.10/lib/bpl/passes/security/cost_modeling.rb:99:in `block (2 levels) in extract_control_blocks': StandardError (StandardError)
        from /usr/lib/ruby/2.3.0/set.rb:306:in `each_key'
        from /usr/lib/ruby/2.3.0/set.rb:306:in `each'
        from /var/lib/gems/2.3.0/gems/bam-bam-boogieman-1.0.10/lib/bpl/passes/security/cost_modeling.rb:96:in `block in extract_control_blocks'
        from /var/lib/gems/2.3.0/gems/bam-bam-boogieman-1.0.10/lib/bpl/passes/security/cost_modeling.rb:95:in `each'
        from /var/lib/gems/2.3.0/gems/bam-bam-boogieman-1.0.10/lib/bpl/passes/security/cost_modeling.rb:95:in `extract_control_blocks'
        from /var/lib/gems/2.3.0/gems/bam-bam-boogieman-1.0.10/lib/bpl/passes/security/cost_modeling.rb:189:in `block in summarize_loops!'
        from /var/lib/gems/2.3.0/gems/bam-bam-boogieman-1.0.10/lib/bpl/passes/security/cost_modeling.rb:171:in `each'
        from /var/lib/gems/2.3.0/gems/bam-bam-boogieman-1.0.10/lib/bpl/passes/security/cost_modeling.rb:171:in `summarize_loops!'
        from /var/lib/gems/2.3.0/gems/bam-bam-boogieman-1.0.10/lib/bpl/passes/security/cost_modeling.rb:280:in `block in run!'
        from /var/lib/gems/2.3.0/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:178:in `yield'
        from /var/lib/gems/2.3.0/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:178:in `block (2 levels) in enumerate_children'
        from /var/lib/gems/2.3.0/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:178:in `each'
        from /var/lib/gems/2.3.0/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:178:in `block in enumerate_children'
        from /var/lib/gems/2.3.0/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:173:in `each'
        from /var/lib/gems/2.3.0/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:173:in `enumerate_children'
        from /var/lib/gems/2.3.0/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:123:in `block in each_child'
        from /var/lib/gems/2.3.0/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:125:in `each'
        from /var/lib/gems/2.3.0/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:125:in `each'
        from /var/lib/gems/2.3.0/gems/bam-bam-boogieman-1.0.10/lib/bpl/ast/node.rb:125:in `each_child'
        from /var/lib/gems/2.3.0/gems/bam-bam-boogieman-1.0.10/lib/bpl/passes/security/cost_modeling.rb:266:in `run!'
        from /var/lib/gems/2.3.0/gems/bam-bam-boogieman-1.0.10/lib/bam.rb:150:in `block (2 levels) in <top (required)>'
        from /var/lib/gems/2.3.0/gems/bam-bam-boogieman-1.0.10/lib/bam.rb:150:in `each'
        from /var/lib/gems/2.3.0/gems/bam-bam-boogieman-1.0.10/lib/bam.rb:150:in `block in <top (required)>'
        from /var/lib/gems/2.3.0/gems/bam-bam-boogieman-1.0.10/lib/bam/prelude.rb:135:in `timed'
        from /var/lib/gems/2.3.0/gems/bam-bam-boogieman-1.0.10/lib/bam.rb:148:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /var/lib/gems/2.3.0/gems/bam-bam-boogieman-1.0.10/exe/bam:4:in `<top (required)>'
        from /usr/local/bin/bam:22:in `load'
        from /usr/local/bin/bam:22:in `<main>'

failed to construct product program
../../lib/ct-verif.mk:53: recipe for target 'secret_indep_wrapper@test_wrapper.c.product.bpl' failed
make: *** [secret_indep_wrapper@test_wrapper.c.product.bpl] Error 255

real    0m1.091s
user    0m0.980s
sys     0m0.113s
```
And I read the line 99 of cost_modeling.rb, there is an annotation "Given a loop, this function returns a tuple containing the loop's control blocks and its (unique) exit block." Does this mean that there can only be one exit in the loop, that is, the "break" keyword needs to be removed?
```
void func (int *p) {
    int i;
    for( i=10; i<20; i++ ) {
        invariant (i >= 0);
        if( p[i] != 0 ){}
    }
}
```
Another different error...
```
Warning: could not resolve constant/variable $load.i32
Error: unidentified parse error: parse error on value "+" ("+")
```
Therefore, I finishly remove the if statement.
```
void func (int *p) {
    int i;
    for( i=10; i<20; i++ ) {
        invariant (i >= 0);
    }
}
```
It finally got to the "verif" stage, but still had the error "Error BP5004: This loop invariant might not hold on entry."
Is there something wrong with my version of smack and bam? Why does such a problem occur?

If you have free time, please give me some advices. Thank you.
